language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get install openjdk-7-jdk

install:
  - easy_install Cython
  - make build_ext

# command to run tests
script:
  - make test
